name: Update Minecraft Client Mappings

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggers

jobs:
  update-mappings:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch and process mappings
      run: |
        python - <<EOF
        import requests
        import json
        
        def get_json(url):
            response = requests.get(url)
            response.raise_for_status()
            return response.json()
        
        # Fetch version manifest
        manifest = get_json('https://launchermeta.mojang.com/mc/game/version_manifest.json')
        
        mappings = {}
        
        for version in manifest['versions']:
            version_id = version['id']
            version_data = get_json(version['url'])
            
            if 'downloads' in version_data and 'client_mappings' in version_data['downloads']:
                mapping_url = version_data['downloads']['client_mappings']['url']
                mapping_data = requests.get(mapping_url).text
                
                mappings[version_id] = mapping_data
        
        with open('minecraft_mappings.json', 'w') as f:
            json.dump(mappings, f, indent=2)
        EOF

    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add minecraft_mappings.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update Minecraft client mappings"; git push)
